name: "banned-terms"
description: "Automatically close issues that contain certain terms."
author: "machiecodes"

branding:
  icon: trash-2
  color: red

inputs:
  config-path:
    description: 'The path to your config JSON file.'
    required: false
    default: '.github/workflows/banned-terms.json'

runs:
  main: 'dist/index.js'
  using: 'node20'

