name: "Banned Words Action"
description: "Automatically close issues that contain certain keywords."
author: "machiecodes"

branding:
  icon: trash-2
  color: red

inputs:
  GITHUB_TOKEN:
    description: "Used to interact with the GitHub API. Typically ${{ secrets.GITHUB_TOKEN }}."
    required: true
    default: "${{ secrets.GITHUB_TOKEN }}"

  banned-words:
    description: "Issues will be closed if they contain any of these words."
    required: true

  close-label:
    description: "Applies this label to automatically closed issues."
    required: false

runs:
  main: 'dist/index.js'
  using: 'node20'

