name: "banned-terms"
description: "Automatically close issues that contain certain terms."
author: "machiecodes"

branding:
  icon: trash-2
  color: red

inputs:
  banned-terms:
    description: "Issues will be closed if they contain any of these words."
    required: true

  close-label:
    description: "Applies this label to automatically closed issues."
    required: false

runs:
  main: 'dist/index.js'
  using: 'node20'

